### ISSUE TITLE
Update Kotlin & Compose

### ISSUE THREAD

**Issue by Wavesonics** [bytebeats/compose-charts#31]
Kotlin 1.8.0 and Compose 1.3.0

**Comment by leinardi** [comment]
@bytebeats do you accept PR? If you do, I can can make one to update the dependencies of the project, including Kotlin and Compose. Please let me know if you are interested.

**Comment by bytebeats** [comment]
> @bytebeats do you accept PR? If you do, I can can make one to update the dependencies of the project, including Kotlin and Compose. Please let me know if you are interested.

Hi @leinardi yes of course, feel free to create PRs. Beyond that, let me know what more do you guys want from this project.

**Comment by leinardi** [comment]
Hi @bytebeats, I just created #32 that bumps all runtime dependencies.

I wasn't able to bump the Android Gradle Plugin to the latest stable because it depends on Gradle 8 and Gradle 8 does not support the current publishing DSL:

```
Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
```

> Beyond that, let me know what more do you guys want from this project.

Yeah, if would be nice if you could first release a new version with the bumped dependencies, after that, in order of priority:

1. Migrate the project to Gradle 8.7 and Android Gradle Plugin 8.4.0 (this will require using the new DSL for publishing the Maven artifact)
2. Provide a Material 3 version of the library
3. Modernize the Gradle project structure making use of version catalog (`libs.versions.toml`)
4. Migrate the Gradle files from Groovy to Kotlin DSL

**Comment by bytebeats** [comment]
@leinardi that's all of really nice ideas! It's also really nice timing to do what you're mentioning. I'd really like to do that!

**Comment by leinardi** [comment]
Nice :slightly_smiling_face:
btw, if you need some inspiration, on this project I have already done some of those tasks, like the Gradle project structure, Kotlin DSL and M3: https://github.com/leinardi/FloatingActionButtonSpeedDial/

**Comment by leinardi** [comment]
Some other things to do could be:
5. Add CI via GitHub Actions
6. Add some static analysis tools like Detekt and Diktat

Both of those things are available on this other project of mine: https://github.com/leinardi/Forlago/blob/master/.github/workflows/ci.yml#L169

**Comment by bytebeats** [comment]
@leinardi your work is really inspiring! I'd like to modernize my project! Really appreciated it!
